#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-adobe-commerce.test}

curl -s https://raw.githubusercontent.com/adobe-commerce/docker-adobe-commerce/develop/lib/template-commerce | bash

bin/setup-commerce "${DOMAIN}"
